name: Compile project and run C++ tests [Linux]
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/test-cpp-linux.yml'
      - 'benchmarks/**'
      - 'examples/**'
      - 'metric/**'
      - 'tests/**'
      - 'CMakeLists.txt'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/test-cpp-linux.yml'
      - 'benchmarks/**'
      - 'examples/**'
      - 'metric/**'
      - 'tests/**'
      - 'CMakeLists.txt'
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [ Debug, Release ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Cache apt
        uses: actions/cache@v2
        env:
          cache-name: cache-apt
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Cache ccache
        uses: actions/cache@v2
        env:
          cache-name: cache-ccache
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.build_type }}

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install cmake
          sudo apt-get install libopenblas-dev
          sudo apt-get install libjpeg-dev
          sudo apt-get install nlohmann-json3-dev
          git clone https://bitbucket.org/blaze-lib/blaze.git --depth=1 --branch=v3.8 && cd blaze && cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ . && sudo make install
          git clone https://github.com/USCiLab/cereal --depth=1 --branch=v1.3.0 && cd cereal && cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ -DJUST_INSTALL_CEREAL=ON . && sudo make install
          sudo apt-get install -y g++-9 g++-9-multilib
          sudo apt-get install ccache
          echo "CC=gcc-9" >> $GITHUB_ENV
          echo "CXX=g++-9" >> $GITHUB_ENV

      - name: Build tests, benchmarks and examples
        run: |
          export MAKE='make -j1'
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DMETRIC_BUILD_TESTS=ON -DMETRIC_BUILD_BENCMARKS=ON -DMETRIC_BUILD_EXAMPLES=ON ../
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
