name: Test C++ code
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'python/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'python/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install system packages
      run: |
        sudo apt-get install ruby-dev
        sudo gem install apt-spy2
        sudo apt-spy2 check
        sudo apt-spy2 fix --commit
        sudo apt-get update
        sudo apt-get install cmake
        sudo apt-get install libboost-all-dev
        sudo apt-get install libopenblas-dev
        sudo apt-get install libjpeg-dev
        sudo apt-get install -y g++-9 g++-9-multilib
        echo "CC=gcc-9" >> $GITHUB_ENV
        echo "CXX=g++-9" >> $GITHUB_ENV
    - name: Build tests and examples
      run: |
        export MAKE='make -j1'
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ../
        make
    - name: Run tests
      run: |
        cd build/tests
        make tests
