name: Test Python package
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cache apt
      uses: actions/cache@v2
      env:
        cache-name: cache-apt
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install cmake
        sudo apt-get install libboost-date-time-dev
        sudo apt-get install libboost-test-dev
        sudo apt-get install libboost-serialization-dev
        sudo apt-get install libboost-iostreams-dev
        sudo apt-get install libopenblas-dev
        sudo apt-get install ccache
        sudo apt-get install -y g++-9 g++-9-multilib
        echo "CC=gcc-9" >> $GITHUB_ENV
        echo "CXX=g++-9" >> $GITHUB_ENV

    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine flake8 auditwheel==3.1.0 pytest numpy

    - name: Lint with flake8 for syntax errors
      run: |
        pip install flake8
        flake8 ./python --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ./python --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Cache ccache
      uses: actions/cache@v2
      env:
        cache-name: cache-ccache
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-build-${{ env.cache-ccache }}

    - name: Build package wheel
      run: |
        cd ./python
        MAKE='make -j1' python setup.py bdist_wheel
        pip install dist/*
    - name: Run tests
      run:
        pytest ./python/tests/
